// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2E69A8PyxwCANpaSouxw4uuzOI1b7Dtw',
    appId: '1:688885675400:android:a2d4aa70431a09ed27b63d',
    messagingSenderId: '688885675400',
    projectId: 'makyaraforum',
    storageBucket: 'makyaraforum.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJYVtQYD5IA2BNmHhucqW59Ekcu0klC6E',
    appId: '1:688885675400:ios:fbbd0a0c2e25e86227b63d',
    messagingSenderId: '688885675400',
    projectId: 'makyaraforum',
    storageBucket: 'makyaraforum.appspot.com',
    iosClientId:
        '688885675400-i155jfvlktknop9f4bqtqksjrkmfimat.apps.googleusercontent.com',
    iosBundleId: 'com.example.dukaApp',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWvoIK9DX9HILupH6fsjKJfelDvD9grmo',
    appId: '1:688885675400:web:b3516bf9449aee3827b63d',
    messagingSenderId: '688885675400',
    projectId: 'makyaraforum',
    authDomain: 'makyaraforum.firebaseapp.com',
    storageBucket: 'makyaraforum.appspot.com',
    measurementId: 'G-SLHK60E7P3',
  );
}
